### ISSUE TITLE
4.8.0 prep branch fails to build when linking against hdf5 1.12.0

### ISSUE THREAD

**Issue by WardF** [Unidata/netcdf-c#1965]
Compiling when linking against hdf5 `1.12.0` fails with an undefined symbol error.  `_H5Literate` referenced from `_rec_read_metadata` in `_hdf5open.c`.  Checking now.

**Comment by WardF** [comment]
It appears that we need to specify `--with-default-api-version=v18` when building libhdf5, which upon reflection I think I already knew.  But we need to check during configure time to ensure that this is checked, instead of failing during linking.

**Comment by ArchangeGabriel** [comment]
This is not the right thing to do. First, since it seems you require HDF5 1.10.6 (HDF5_VERSION_1106), shouldn’t that be v110 API you want?

Also, recompiling HDF5 like this is not a good idea if other projects use it. Rather, you should define `-DH5_USE_18_API` in `CPPFLAGS` (or `-DH5_USE_110_API` if using 1.10.x API).

**Comment by ArchangeGabriel** [comment]
Also, they are two warning related to the use of `_H5Literate`:
```
/build/netcdf/src/netcdf-c-4.8.0/h5_test/tst_h_files4.c: In function ‘main’:
/build/netcdf/src/netcdf-c-4.8.0/h5_test/tst_h_files4.c:167:64: warning: passing argument 5 of ‘H5Literate1’ from incompatible pointer type [-Wincompatible-pointer-types]
  167 |   if (H5Literate(grpid, H5_INDEX_CRT_ORDER, H5_ITER_INC, &idx, op_func,
      |                                                                ^~~~~~~
      |                                                                |
      |                                                                herr_t (*)(hid_t,  const char *, const H5L_info2_t *, void *) {aka int (*)(long int,  const char *, const H5L_info2_t *, void *)}
In file included from /usr/include/H5Opublic.h:31,
                 from /usr/include/H5Apublic.h:22,
                 from /usr/include/hdf5.h:23,
                 from /build/netcdf/src/netcdf-c-4.8.0/h5_test/tst_h_files4.c:11:
/usr/include/H5Lpublic.h:255:57: note: expected ‘H5L_iterate1_t’ {aka ‘int (*)(long int,  const char *, const H5L_info1_t *, void *)’} but argument is of type ‘herr_t (*)(hid_t,  const char *, const H5L_info2_t *, void *)’ {aka ‘int (*)(long int,  const char *, const H5L_info2_t *, void *)’}
  255 |     H5_iter_order_t order, hsize_t *idx, H5L_iterate1_t op, void *op_data);
      |                                          ~~~~~~~~~~~~~~~^~
```
and
```
/build/netcdf/src/netcdf-c-4.8.0/h5_test/tst_h_atts3.c: In function ‘main’:
/build/netcdf/src/netcdf-c-4.8.0/h5_test/tst_h_atts3.c:282:37: warning: passing argument 6 of ‘H5Oget_info_by_idx3’ from incompatible pointer type [-Wincompatible-pointer-types]
  282 |                                  i, &obj_info, H5O_INFO_BASIC, H5P_DEFAULT) < 0) ERR;
      |                                     ^~~~~~~~~
      |                                     |
      |                                     H5O_info1_t *
In file included from /usr/include/H5Apublic.h:22,
                 from /usr/include/hdf5.h:23,
                 from /build/netcdf/src/netcdf-c-4.8.0/h5_test/tst_h_atts3.c:14:
/usr/include/H5Opublic.h:191:73: note: expected ‘H5O_info2_t *’ but argument is of type ‘H5O_info1_t *’
  191 |     H5_index_t idx_type, H5_iter_order_t order, hsize_t n, H5O_info2_t *oinfo,
      |                                                            ~~~~~~~~~~~~~^~~~~
```

**Comment by ArchangeGabriel** [comment]
For what it’s worth, `-DH5_USE_110_API` indeed works.

**Comment by dkokron** [comment]
This issue has reappeared with hdf-1.14.2+netcdf-4.9.2.

ftn    -m64 -mcmodel=small -pthread -threads -Wl,--no-as-needed  -qopenmp -L/lfs/h3/hpc/support/USER/Projects/hpc-stack/install/intel-19.1.3.304/cray-mpich-8.1.19/hdf5/1.14.2/lib   -L/lfs/h3/hpc/support/USER/Projects/hpc-stack/install/intel-19.1.3.304/zlib/1.2.11/lib -L/lfs/h3/hpc/support/USER/Projects/hpc-stack/install/intel-19.1.3.304/cray-mpich-8.1.19/esmf/8.4.2/lib -L/lfs/h3/hpc/support/USER/Projects/hpc-stack/install/intel-19.1.3.304/cray-mpich-8.1.19/netcdf/4.9.2/lib  -Wl,-rpath,/lfs/h3/hpc/support/USER/Projects/hpc-stack/install/intel-19.1.3.304/cray-mpich-8.1.19/esmf/8.4.2/lib -Wl,-rpath,/lfs/h3/hpc/support/USER/Projects/hpc-stack/install/intel-19.1.3.304/cray-mpich-8.1.19/netcdf/4.9.2/lib  -o /lfs/h3/hpc/support/USER/Projects/hpc-stack/install/intel-19.1.3.304/cray-mpich-8.1.19/esmf/8.4.2/bin/ESMF_PrintInfo /u/USER/S3/Projects/hpc-stack/pkg/v8.4.2/obj/objO/Linux.intel.64.mpich.default/src/apps/ESMF_PrintInfo/ESMF_PrintInfo.o -lesmf  -cxxlib -lrt -ldl -lnetcdff -lnetcdf -lhdf5_hl -lhdf5  -lz -ldl -lm  -lpioc
/usr/lib64/gcc/x86_64-suse-linux/7/../../../../x86_64-suse-linux/bin/ld: /lfs/h3/hpc/support/USER/Projects/hpc-stack/install/intel-19.1.3.304/cray-mpich-8.1.19/netcdf/4.9.2/lib/libnetcdf.a(libnchdf5_la-hdf5open.o): in function `rec_read_metadata':
hdf5open.c:(.text+0x22f): undefined reference to `H5Literate'


nm /lfs/h3/hpc/support/USER/Projects/hpc-stack/install/intel-19.1.3.304/cray-mpich-8.1.19/hdf5/1.14.2/lib/libhdf5.a | grep H5Literate
0000000000005c10 T H5Literate2
0000000000005fd0 T H5Literate_async
0000000000006530 T H5Literate_by_name2
00000000000000d0 T H5Literate1
0000000000000500 T H5Literate_by_name1

**Comment by WardF** [comment]
@dkokron Do you have the `config.log` generated when configuring netCDF-C against hdf5 `1.14.2`? My initial attempts are failing to recreate this issue.

**Comment by dkokron** [comment]
NetCDF-4.9.2 builds fine with hdf-1.14.2.  This is a link time failure.  I'm testing now with a hacked netcdf-c-4.9.2/libhdf5/hdf5open.c

diff --git a/libhdf5/hdf5open.c b/libhdf5/hdf5open.c
index cb2491ff..e80d7768 100644
--- a/libhdf5/hdf5open.c
+++ b/libhdf5/hdf5open.c
@@ -2898,7 +2898,7 @@ rec_read_metadata(NC_GRP_INFO_T *grp)
      * passed as a parameter to the callback function
      * read_hdf5_obj(). (I have also tried H5Oiterate(), but it is much
      * slower iterating over the same file - Ed.) */
-    if (H5Literate(hdf5_grp->hdf_grpid, iter_index, H5_ITER_INC, &idx,
+    if (H5Literate2(hdf5_grp->hdf_grpid, iter_index, H5_ITER_INC, &idx,
                    read_hdf5_obj, (void *)&udata) < 0)
         BAIL(NC_EHDFERR);

**Comment by dkokron** [comment]
The above hack allowed me to successfully build ESMF-8.4.2 which builds a couple executables at the end.  The ESMF_PrintInfo applications in particular was failing with the above link time error before modifying netcdf-c-4.9.2/libhdf5/hdf5open.c

**Comment by dkokron** [comment]
Since you asked for the config.log.
[config.log](https://github.com/Unidata/netcdf-c/files/13035169/config.log)

**Comment by edwardhartnett** [comment]
OK, the correct answer is to not use any of the HDF5 macros that change function names in a poor mockery of backward compatibility.

Instead, what works best is to change the function to one of the actual functions (H5Linterate1() probably). Then it does not matter what macro is set or what default API is used on HDF5. We cannot fully control how HDF5 is built, and using these macros just adds confusion.

I will see if I can submit a PR with this change in time for 4.9.3.
