### ISSUE TITLE
Failing builds with S3 enabled

### ISSUE THREAD

**Issue by mannreis** [Unidata/netcdf-c#3147]
Since https://github.com/Unidata/netcdf-c/pull/3090 compiling netcdf when S3 switches are enabled fails for both:
autotools: `./configure --enable-s3 --enable-nczarr` (uses `aws-sdk-cpp`)
cmake: `cmake ../ -DNETCDF_ENABLE_NCZARR=ON -DNETCDF_ENABLE_S3_INTERNAL=ON` (uses internal `s3` implementation)
These are the sort of errors one immediately gets:
```
nch5s3comms.c:95:10: fatal error: netcdf_vutils.h: No such file or directory
   95 | #include "netcdf_vutils.h"
```
```
zmap_s3sdk.c:264:24: error: too many arguments to function ‘NC_s3sdkclose’
  264 |     if(s3client) {stat=NC_s3sdkclose(s3client,&info,1,NULL);}
```
```
zmap_s3sdk.c:410:9: error: too many arguments to function ‘NC_s3sdkclose’
  410 |         NC_s3sdkclose(z3map->s3client, &z3map->s3, deleteit, &z3map->errmsg);
```

I created https://github.com/Unidata/netcdf-c/pull/3122 hoping to fix the problem but also enable these builds on github actions. IMO this build variant should be exercised as well.

**Comment by WardF** [comment]
Thank you; I'm taking a look at #3090 and this as well!

**Comment by WardF** [comment]
I'm looking to figure out what happened, this was working in `v4.9.3`, and the files immediately involved don't appear to have changed.  I'll follow up.
