### ISSUE TITLE
Duplicate symbol isinf and isnan on macOS using Intel OneAPI 

### ISSUE THREAD

**Issue by kgerheiser** [Unidata/netcdf-c#2132]
I'm building NetCDF 4.8.1 and I'm getting duplicate symbol on macOS (11.6.0, XCode 13.0) using Intel OneAPI 2021.2.0.

```
duplicate symbol '_isinf' in:
    ../libdispatch/.libs/libdispatch.a(libdispatch_la-dutil.o)
    /opt/intel/oneapi/compiler/2021.2.0/mac/bin/intel64/../../compiler/lib/libimf.a(isinf.o)
duplicate symbol '_isnan' in:
    ../libdispatch/.libs/libdispatch.a(libdispatch_la-dutil.o)
    /opt/intel/oneapi/compiler/2021.2.0/mac/bin/intel64/../../compiler/lib/libimf.a(isnan.o)
ld: 2 duplicate symbols for architecture x86_64
```

Intel declares `isnan` and `isInf` in `libimf`, and NetCDF declares it here (for \_\_APPLE\_\_ only):

https://github.com/Unidata/netcdf-c/blob/228e7f5b5c96ef66df0d94a99414519fb3a8288c/libdispatch/dutil.c#L358

Not sure why that's necessary in the first place, but if it's required maybe it should check if `__APPLE__` and also not `__INTEL_COMPILER `.

**Comment by DennisHeimbigner** [comment]
Fixed by https://github.com/Unidata/netcdf-c/pull/2138

**Comment by MicroTed** [comment]
I almost opened a new issue, but found this one....

When compiling 4.9.0 on macos (big sur) with FC=ifort CC=clang (13.0), configure sets HAVE_DECL_ISINF=1. The logic in dutil.c around the isinf/isnan functions does not use this flag, but instead has

```
#if ! defined __INTEL_COMPILER 
#if defined __APPLE__ 
```

which causes the isinf/isnan code to be included and can result in a link error for duplicate definition. (It works correctly if CC=icc instead of clang). I recompiled after inserting an additional condition on HAVE_DECL_ISINF into dutil.c, and it seems to work fine. 

Obviously netcdf-c doesn't use the fortran compiler, but I set FC out of habit and it probably has no effect. Is there a reason not to use the HAVE_DECL_ISINF flag in dutil.c?

It is also possible that there is still something screwy in my system (just updated to Big Sur), but excluding those functions fixed a duplicate symbol error I got when compiling WRF.

**Comment by WardF** [comment]
I'm working on getting `v4.9.1-rc2` out the door right now, this seems like a straightforward fix, and I'm working on MacOS so it should be easy to test.  Thanks!

**Comment by MicroTed** [comment]
I should add one detail that I was compiling with --disable-shared, which may or may not make any difference in linking error.  Also 'make check' was happy in either case (before/after change to dutil.c), so I don't really know.

I think I just used the conditional in include/isnan.h:

#if ! (defined(isinf) || HAVE_DECL_ISINF)
