### ISSUE TITLE
Link fails with autotools on OSX

### ISSUE THREAD

**Issue by WardF** [Unidata/netcdf-c#223]
Currently observing the following in `master` when attempting to build w/ `configure/make` on OSX 10.11.

This is not occurring on Linux, or on OSX with CMake.

Issue seems straightforward but requires some debugging.  Potential avenues for investigation:

* `clang` vs. `gcc`
* `static` vs. `shared` build

## Error observed:

`````.bash
duplicate symbol _nc4_hdf5_initialized in:
    ../libsrc4/.libs/libnetcdf4.a(libnetcdf4_la-nc4attr.o)
    ../libsrc4/.libs/libnetcdf4.a(libnetcdf4_la-nc4dim.o)
duplicate symbol _nc4_hdf5_initialized in:
    ../libsrc4/.libs/libnetcdf4.a(libnetcdf4_la-nc4attr.o)
    ../libsrc4/.libs/libnetcdf4.a(libnetcdf4_la-nc4file.o)
duplicate symbol _nc4_hdf5_initialized in:
    ../libsrc4/.libs/libnetcdf4.a(libnetcdf4_la-nc4attr.o)
    ../libsrc4/.libs/libnetcdf4.a(libnetcdf4_la-nc4grp.o)
duplicate symbol _nc4_hdf5_initialized in:
    ../libsrc4/.libs/libnetcdf4.a(libnetcdf4_la-nc4attr.o)
    ../libsrc4/.libs/libnetcdf4.a(libnetcdf4_la-nc4hdf.o)
duplicate symbol _nc4_hdf5_initialized in:
    ../libsrc4/.libs/libnetcdf4.a(libnetcdf4_la-nc4attr.o)
    ../libsrc4/.libs/libnetcdf4.a(libnetcdf4_la-nc4internal.o)
duplicate symbol _nc4_hdf5_initialized in:
    ../libsrc4/.libs/libnetcdf4.a(libnetcdf4_la-nc4attr.o)
    ../libsrc4/.libs/libnetcdf4.a(libnetcdf4_la-nc4type.o)
duplicate symbol _nc4_hdf5_initialized in:
    ../libsrc4/.libs/libnetcdf4.a(libnetcdf4_la-nc4attr.o)
    ../libsrc4/.libs/libnetcdf4.a(libnetcdf4_la-nc4var.o)
duplicate symbol _nc4_hdf5_initialized in:
    ../libsrc4/.libs/libnetcdf4.a(libnetcdf4_la-nc4attr.o)
    ../libsrc4/.libs/libnetcdf4.a(libnetcdf4_la-ncfunc.o)
ld: 8 duplicate symbols for architecture x86_64
`````

**Comment by WardF** [comment]
Fails on OSX w/ `clang` and `gcc`, for all valid permutations of `--[enable/disable]-[shared/static]`, when using autotools.

**Comment by WardF** [comment]
Using the attached script for a `git bisect` operation, I've observed the following results.  It's very strange this is only manifesting on OSX.

* git bisect script:  [gh223.sh.gz](https://github.com/Unidata/netcdf-c/files/138665/gh223.sh.gz)

`````.C
b5ba4247939b637c2371e38bb594dbc476c0f8f3 is the first bad commit
commit b5ba4247939b637c2371e38bb594dbc476c0f8f3
Author: Dennis Heimbigner <dmh@ucar.edu>
Date:   Thu Jan 28 15:03:40 2016 -0700

    Clean up the handling of hdf5 initialization by
    creating an nc4_hdf5_initialize(void) function
    plus nc4_hdf5_initialized flag.
    Also fix potential null exception in nc4internal.c

:040000 040000 230458d78e67033b5af13a8207da560e39ed0640 f4c46e7841648c7bf8f433b797915ff03ece6c5f M	include
:040000 040000 fc54ddc39587c09ec6d381ec3a87526b08c82e65 dab001946fcbc9f317546ac5a748202a957b00c7 M	libsrc4
bisect run success
`````
