### ISSUE TITLE
Build failure with hdf5-2.2.0

### ISSUE THREAD

**Issue by xelaseer** [Unidata/netcdf-c#3450]
To report a non-security related issue, please provide:

* netcdf-4.9.3
* Gentoo linux x86_64 - systemd/gnome stack. GCC 16.1, hdf5-2.2.0
* attempt to build with hdf5-2.2.0 - build failure

This is results in a 100% reproducible build failure on my system with the following error:

FAILED: [code=1] libhdf5/CMakeFiles/netcdfhdf5.dir/H5FDhttp.c.o 
 530 │ /usr/bin/x86_64-pc-linux-gnu-gcc -DH5_BUILT_AS_DYNAMIC_LIB -DHAVE_CONFIG_H -D_FILE_OFFSET_BITS=64 -D_GNU_SOURCE -D_LARGEFILE_SOURCE -D_POSIX_C_SOURCE=200809L -I/var/tmp/portage/sci-libs/netcdf-4.9.3-r2/work/netcdf-c-4.9.3_build/include -I/var/tmp/portage/sci-libs/netcdf-4.9.3
     │ -r2/work/netcdf-c-4.9.3/include -I/var/tmp/portage/sci-libs/netcdf-4.9.3-r2/work/netcdf-c-4.9.3/oc2 -I/var/tmp/portage/sci-libs/netcdf-4.9.3-r2/work/netcdf-c-4.9.3/libsrc -I/var/tmp/portage/sci-libs/netcdf-4.9.3-r2/work/netcdf-c-4.9.3_build  -march=native -O3 -flto -pipe -fgr
     │ aphite-identity -floop-nest-optimize -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 -fPIC -MD -MT libhdf5/CMakeFiles/netcdfhdf5.dir/H5FDhttp.c.o -MF libhdf5/CMakeFiles/netcdfhdf5.dir/H5FDhttp.c.o.d -o libhdf5/CMakeFiles/netcdfhdf5.dir/H5FDhttp.c.o -c /var/tmp/portage/sci-libs/n
     │ etcdf-4.9.3-r2/work/netcdf-c-4.9.3/libhdf5/H5FDhttp.c
 531 │ /var/tmp/portage/sci-libs/netcdf-4.9.3-r2/work/netcdf-c-4.9.3/libhdf5/H5FDhttp.c:57:2: error: #error "Cannot determine version of H5FD_class_t"
 532 │    57 | #error "Cannot determine version of H5FD_class_t"
 533 │       |  ^~~~~
 534 │ In file included from /var/tmp/portage/sci-libs/netcdf-4.9.3-r2/work/netcdf-c-4.9.3/libhdf5/H5FDhttp.c:75:
 535 │ /var/tmp/portage/sci-libs/netcdf-4.9.3-r2/work/netcdf-c-4.9.3/libhdf5/H5FDhttp.c: In function ‘H5Pset_fapl_http’:
 536 │ /var/tmp/portage/sci-libs/netcdf-4.9.3-r2/work/netcdf-c-4.9.3/libhdf5/H5FDhttp.h:34:26: error: implicit declaration of function ‘H5FDperform_init’ [-Wimplicit-function-declaration]
 537 │    34 | #define H5FD_HTTP       (H5FDperform_init(H5FD_http_init))
 538 │       |                          ^~~~~~~~~~~~~~~~
 539 │ /var/tmp/portage/sci-libs/netcdf-4.9.3-r2/work/netcdf-c-4.9.3/libhdf5/H5FDhttp.c:316:35: note: in expansion of macro ‘H5FD_HTTP’
 540 │   316 |     return H5Pset_driver(fapl_id, H5FD_HTTP, NULL);
 541 │       |                                   ^~~~~~~~~

[build.log](https://github.com/user-attachments/files/31940139/build.log)

[emerge-info.txt](https://github.com/user-attachments/files/31940148/emerge-info.txt)

**Comment by kobboi** [comment]
Current main branch compiles file with hdf5-2.2.0. ~~There just has not been a new release including this~~. I missed the 4.10.0 and 4.10.1 tags because of alphabetic sorting.

A mindless bump in Gentoo to 4.10.1 seems to compile fine, or at least does not hit this problem.

Propose to close

**Comment by WardF** [comment]
Thanks! I saw your original comment and was just coming to ask for more info, as 4.10.x was working for me :). Thanks!
