### PR TITLE
Provide byte-range reading of remote datasets

### PR DESCRIPTION
**Pull request by DennisHeimbigner**
* Fixes https://github.com/Unidata/netcdf-c/issues/1251

Assume that you have the URL to a remote dataset
which is a normal netcdf-3 or netcdf-4 file.

This PR allows the netcdf-c to read that dataset's
contents as a netcdf file using HTTP byte ranges
if the remote server supports byte-range access.

Originally, this PR was set up to access Amazon S3 objects,
but it can also access other remote datasets such as those
provided by a Thredds server via the HTTPServer access protocol.
It may also work for other kinds of servers.

Note that this is not intended as a true production
capability because, as is known, this kind of access to
can be quite slow. In addition, the byte-range IO drivers
do not currently do any sort of optimization or caching.

An additional goal here is to gain some experience with
the Amazon S3 REST protocol.

This architecture and its use documented in
the file docs/byterange.dox.

There are currently two test cases:

1. nc_test/tst_s3raw.c - this does a simple open, check format, close cycle
   for a remote netcdf-3 file and a remote netcdf-4 file.
2. nc_test/test_s3raw.sh - this uses ncdump to investigate some remote
   datasets.

This PR also incorporates significantly changed model inference code
(see the superceded PR https://github.com/Unidata/netcdf-c/pull/1259).

1. It centralizes the code that infers the dispatcher.
2. It adds support for byte-range URLs

Other changes:

1. NC_HDF5_finalize was not being properly called by nc_finalize().
2. Fix minor bug in ncgen3.l
3. fix memory leak in nc4info.c
4. add code to walk the .daprc triples and to replace protocol=
   fragment tag with a more general mode= tag.

Final Note:
Th inference code is still way too complicated. We need to move
to the validfile() model used by netcdf Java, where each
dispatcher is asked if it can process the file. This decentralizes
the inference code. This will be done after all the major new
dispatchers (PIO, Zarr, etc) have been implemented.

### CODE REVIEW

**Comment by WardF** [comment]
This pull request **introduces 2 alerts** when merging bf2746b8eaa17a35126f105a14da186cbce84d92 into b16eceabe27ef334d4384eae07387cbac18d2afc - [view on LGTM.com](https://lgtm.com/projects/g/Unidata/netcdf-c/rev/pr-6be0504cfb44e35850ad5f55d3668c12d21bd9b4)

**new alerts:**

* 2 for Empty branch of conditional

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by DennisHeimbigner** [comment]
Ok, I fixed the alerts, but I am baffled by the appveyor complaint.
It looks like we have amismatch between a struct and the initializers for it.
But I cannot see the mismatch. Even a count of the fields seems to be ok.

**Comment by DennisHeimbigner** [comment]
Ok, so I compared the problem structure (in H5FDpublic.h) for versions 1.8.17
and 1.10.3, and they differ. So I need to do some conditionals depending on the
HDF5 version. My guess is that the change occurred between 1.8 and 1.10.

**Comment by WardF** [comment]
Merged in modifications from `master`, seeing a failure in builds using `mpicc`.  Going to add a single instance (non comprehensive for now) of parallel builds to travis to catch compilation errors, will follow up here with more info as I go back and sort it out.

**Comment by WardF** [comment]
Seeing failures in the following tests when running which `mpicc` provided by `mpich`.

````
The following tests FAILED:
	 46 - nc_test_run_pnetcdf_test (Failed)
	 47 - nc_test_tst_formatx_pnetcdf (Failed)
	 50 - nc_test_tst_small (Failed)
	 52 - nc_test_tst_norm (Failed)
	 54 - nc_test_tst_nofill (Failed)
	 68 - nc_test (Child aborted)
	136 - nc_test4_tst_atts3 (Failed)
````

Details available at http://cdash.unidata.ucar.edu/viewTest.php?onlyfailed&buildid=7195

**Comment by DennisHeimbigner** [comment]
Added fixes for the parallel case.

File: libdispatch/dinfermodel.c [hunk 1]
```diff
@@ -0,0 +1,1024 @@
...
+
+    /* Process the cmode; may override some already set flags */
+    if(fIsSet(cmode,NC_64BIT_OFFSET)) {
+	conflictset(MF,model->format,NC_FORMAT_64BIT_OFFSET);
+    }
+    if(fIsSet(cmode,NC_64BIT_DATA)) {
+	conflictset(MF,model->format,NC_FORMAT_64BIT_DATA);
+    }
+    if(fIsSet(cmode,NC_NETCDF4)) {
+	conflictset(MF,model->format,NC_FORMAT_NETCDF4);
```
Comment (mathstuf) [inline libdispatch/dinfermodel.c]: I'm looking at an issue where passing `NC_NOWRITE | NC_64BIT_OFFSET | NC_NETCDF4 | NC_CLASSIC_MODEL` flags worked in 4.6.2, but fails in 4.7.0 in this function. It seems to be detecting that we have the `NC_FORMAT_64BIT_OFFSET` as the format and then fails here because the format has already been set. Is this intended? Should it have worked before?

**Comment by DennisHeimbigner** [comment]
I would say that since NC_64BIT_OFFSET => classic format
that also specifying NC_NETCDF4 should be an error.

**Comment by mathstuf** [comment]
Thanks. Removing the `NC_64BIT_OFFSET` flag worked with the tests we have.
