### ISSUE TITLE
conflicting types for MPI_Comm

### ISSUE THREAD

**Issue by pedmon** [Unidata/netcdf-c#2673]
I'm working on building netcdf-c 4.9.2 on Rocky 8.7 with gcc 12.2.0, openmpi 4.1.4 and hdf5 1.14.0.  hdf5 has been built with parallel support but when I build netcdf-c I get:

```bash
In file included from /n/sw/helmod-rocky8/apps/MPI/gcc/12.2.0-fasrc01/openmpi/4.1.4-fasrc01/hdf5/1.14.0-fasrc01/include/H5public.h:65,
                 from /n/sw/helmod-rocky8/apps/MPI/gcc/12.2.0-fasrc01/openmpi/4.1.4-fasrc01/hdf5/1.14.0-fasrc01/include/hdf5.h:21,
                 from dvarinq.c:14:
/n/sw/helmod-rocky8/apps/Comp/gcc/12.2.0-fasrc01/openmpi/4.1.4-fasrc01/include/mpi.h:419:37: error: conflicting types for 'MPI_Comm'; have 'struct ompi_communicator_t *'
  419 | typedef struct ompi_communicator_t *MPI_Comm;
      |                                     ^~~~~~~~
In file included from dvarinq.c:11:
../include/ncdispatch.h:84:13: note: previous declaration of 'MPI_Comm' with type 'MPI_Comm' {aka 'int'}
   84 | typedef int MPI_Comm;
      |             ^~~~~~~~
```
A quick search showed that this has happened in the past but had been resolved in previous versions, though it appears to have crept back in.

My build line looks like:

```bash
+ export CC=mpicc CXX=mpicxx FC=mpif90 F77=mpif77
+ CC=mpicc
+ CXX=mpicxx
+ FC=mpif90
+ F77=mpif77
+ ./configure --prefix=/n/sw/helmod-rocky8/apps/MPI/gcc/12.2.0-fasrc01/openmpi/4.1.4-fasrc01/netcdf-c/4.9.2-fasrc01 --program-prefix= --exec-prefix=/n/sw/helmod-rocky8/apps/MPI/gcc/12.2.0-fasrc01/openmpi/4.1.4-fasrc01/netcdf-c/4.9.2-fasrc01 --bindir=/n/sw/helmod-rocky8/apps/MPI/gcc/12.2.0-fasrc01/openmpi/4.1.4-fasrc01/netcdf-c/4.9.2-fasrc01/bin --sbindir=/n/sw/helmod-rocky8/apps/MPI/gcc/12.2.0-fasrc01/openmpi/4.1.4-fasrc01/netcdf-c/4.9.2-fasrc01/sbin --sysconfdir=/n/sw/helmod-rocky8/apps/MPI/gcc/12.2.0-fasrc01/openmpi/4.1.4-fasrc01/netcdf-c/4.9.2-fasrc01/etc --datadir=/n/sw/helmod-rocky8/apps/MPI/gcc/12.2.0-fasrc01/openmpi/4.1.4-fasrc01/netcdf-c/4.9.2-fasrc01/share --includedir=/n/sw/helmod-rocky8/apps/MPI/gcc/12.2.0-fasrc01/openmpi/4.1.4-fasrc01/netcdf-c/4.9.2-fasrc01/include --libdir=/n/sw/helmod-rocky8/apps/MPI/gcc/12.2.0-fasrc01/openmpi/4.1.4-fasrc01/netcdf-c/4.9.2-fasrc01/lib64 --libexecdir=/n/sw/helmod-rocky8/apps/MPI/gcc/12.2.0-fasrc01/openmpi/4.1.4-fasrc01/netcdf-c/4.9.2-fasrc01/libexec --localstatedir=/n/sw/helmod-rocky8/apps/MPI/gcc/12.2.0-fasrc01/openmpi/4.1.4-fasrc01/netcdf-c/4.9.2-fasrc01/var --sharedstatedir=/n/sw/helmod-rocky8/apps/MPI/gcc/12.2.0-fasrc01/openmpi/4.1.4-fasrc01/netcdf-c/4.9.2-fasrc01/var/lib --mandir=/n/sw/helmod-rocky8/apps/MPI/gcc/12.2.0-fasrc01/openmpi/4.1.4-fasrc01/netcdf-c/4.9.2-fasrc01/share/man --infodir=/n/sw/helmod-rocky8/apps/MPI/gcc/12.2.0-fasrc01/openmpi/4.1.4-fasrc01/netcdf-c/4.9.2-fasrc01/share/info --enable-netcdf-4 --with-temp-large=/scratch
```

This works fine with Intel 23 and OpenMPI 4.1.4 so its something to do with the way gcc is handling things.

**Comment by DennisHeimbigner** [comment]
This is the same as this, correct?
> https://github.com/Unidata/netcdf-c/issues/24

**Comment by pedmon** [comment]
Yes, same type of error. It was resolved in that previous version 9 years ago but is now reoccurring for the above stack. This is using configure instead of cmake in this instance.

**Comment by edwardhartnett** [comment]
Can you post the contents of include/netcdf_meta.h here please?

**Comment by edwardhartnett** [comment]
As we see here:

#define NC_HAS_PARALLEL4 0 /*!< parallel IO support via HDF5 */
#define NC_HAS_PARALLEL  0 /*!< parallel IO support via HDF5 and/or PnetCDF. */


Netcdf was not built for parallel I/O.

In order to build netCDF with parallel I/O it must be pointed at a HDF5 that has been built with MPI and option --enable-parallel, So make sure your HDF5 is built with parallel I/O and then rebuild netCDF.

**Comment by pedmon** [comment]
It is most definitely being built against an hdf5 built with MPI and --enable-parallel. This is the configure line I used for hdf5:

```bash
export CONFIGOPTS="--enable-fortran --enable-shared --enable-static "
test "%{type}" == "MPI" && CONFIGOPTS="${CONFIGOPTS} --enable-parallel" ||  CONFIGOPTS="${CONFIGOPTS} --enable-cxx"
test "%{type}" == "MPI" && export CC=mpicc CXX=mpicxx FC=mpif90

./configure --prefix=%{_prefix} \
        --enable-fortran --enable-shared --enable-static \
        --with-szlib="$SZIP_INCLUDE,$SZIP_LIB" \
        --with-zlib="$ZLIB_INCLUDE,$ZLIB_LIB" ${CONFIGOPTS}
```
From the config.log for hdf5

```bash
            SUMMARY OF THE HDF5 CONFIGURATION
            =================================

General Information:
-------------------
                   HDF5 Version: 1.14.0
                  Configured on: Tue Apr 11 10:07:10 EDT 2023
                  Configured by: pedmon@builds01.rc.fas.harvard.edu
                    Host system: x86_64-unknown-linux-gnu
              Uname information: Linux builds01.rc.fas.harvard.edu 4.18.0-425.10.1.el8_7.x86_64 #1 SMP Thu Jan 12 16:32:13 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
                       Byte sex: little-endian
             Installation point: /n/sw/helmod-rocky8/apps/MPI/gcc/12.2.0-fasrc01/openmpi/4.1.4-fasrc01/hdf5/1.14.0-fasrc01

Compiling Options:
------------------
                     Build Mode: production
              Debugging Symbols: no
                        Asserts: no
                      Profiling: no
             Optimization Level: high

Linking Options:
----------------
                      Libraries: static, shared
  Statically Linked Executables:
                        LDFLAGS:
                     H5_LDFLAGS:
                     AM_LDFLAGS:  -L/n/sw/helmod-rocky8/apps/Core/zlib/1.2.13-fasrc01/lib -L/n/sw/helmod-rocky8/apps/Core/szip/2.1.1-fasrc01/lib64
                Extra libraries: -lsz -lz -ldl -lm
                       Archiver: ar
                       AR_FLAGS: cr
                         Ranlib: ranlib

Languages:
----------
                              C: yes
                     C Compiler: /n/sw/helmod-rocky8/apps/Comp/gcc/12.2.0-fasrc01/openmpi/4.1.4-fasrc01/bin/mpicc ( built with gcc version 12.2.0 (GCC))
                       CPPFLAGS:
                    H5_CPPFLAGS: -D_GNU_SOURCE -D_POSIX_C_SOURCE=200809L   -DNDEBUG -UH5_DEBUG_API
                    AM_CPPFLAGS:  -I/n/sw/helmod-rocky8/apps/Core/zlib/1.2.13-fasrc01/include -I/n/sw/helmod-rocky8/apps/Core/szip/2.1.1-fasrc01/include -I/builds/pedmon/helmod/rpmbuild/BUILD/hdf5-1.14.0/src/H5FDsubfiling
                        C Flags:
                     H5 C Flags:  -std=c99  -Wall -Wcast-qual -Wconversion -Wextra -Wfloat-equal -Wformat=2 -Winit-self -Winvalid-pch -Wmissing-include-dirs -Wshadow -Wundef -Wwrite-strings -pedantic -Wno-c++-compat -Wlarger-than=2560 -Wlogical-op -Wframe-larger-than=16384 -Wpacked-bitfield-compat -Wsync-nand -Wno-unsuffixed-float-constants -Wdouble-promotion -Wtrampolines -Wstack-usage=8192 -Wmaybe-uninitialized -Wdate-time -Warray-bounds=2 -Wc99-c11-compat -Wduplicated-cond -Whsa -Wnormalized -Wnull-dereference -Wunused-const-variable -Walloca -Walloc-zero -Wduplicated-branches -Wformat-overflow=2 -Wformat-truncation=1 -Wattribute-alias -Wcast-align=strict -Wshift-overflow=2 -Wattribute-alias=2 -Wmissing-profile -Wc11-c2x-compat -fstdarg-opt -fdiagnostics-urls=never -fno-diagnostics-color -s  -Wbad-function-cast -Wcast-align -Wformat -Wimplicit-function-declaration -Wint-to-pointer-cast -Wmissing-declarations -Wmissing-prototypes -Wnested-externs -Wold-style-definition -Wpacked -Wpointer-sign -Wpointer-to-int-cast -Wredundant-decls -Wstrict-prototypes -Wswitch -Wunused-but-set-variable -Wunused-variable -Wunused-function -Wunused-parameter -Wincompatible-pointer-types -Wint-conversion -Wshadow -Wrestrict -Wcast-function-type -Wmaybe-uninitialized -Wno-aggregate-return -Wno-inline -Wno-missing-format-attribute -Wno-missing-noreturn -Wno-overlength-strings -Wno-jump-misses-init -Wstrict-overflow=2 -Wno-suggest-attribute=const -Wno-suggest-attribute=noreturn -Wno-suggest-attribute=pure -Wno-suggest-attribute=format -Wno-suggest-attribute=cold -Wno-suggest-attribute=malloc -O3
                     AM C Flags:
               Shared C Library: yes
               Static C Library: yes


                        Fortran: yes
               Fortran Compiler: /n/sw/helmod-rocky8/apps/Comp/gcc/12.2.0-fasrc01/openmpi/4.1.4-fasrc01/bin/mpif90 ( built with gcc version 12.2.0 (GCC))
                  Fortran Flags:
               H5 Fortran Flags:  -std=f2008  -Waliasing -Wall -Wcharacter-truncation -Wextra -Wimplicit-interface -Wsurprising -Wunderflow -pedantic -Warray-temporaries -Wintrinsics-std -Wimplicit-procedure -Wreal-q-constant -Wfunction-elimination -Wrealloc-lhs -Wrealloc-lhs-all -Wno-c-binding-type -Winteger-division -Wfrontend-loop-interchange  -fdiagnostics-urls=never -fno-diagnostics-color -s  -Wno-unused-dummy-argument -O3
               AM Fortran Flags:
         Shared Fortran Library: yes
         Static Fortran Library: yes
               Module Directory: ${includedir}

                            C++: no

                           Java: no


Features:
---------
                     Parallel HDF5: yes
  Parallel Filtered Dataset Writes: yes
                Large Parallel I/O: yes
                High-level library: yes
Dimension scales w/ new references: no
                  Build HDF5 Tests: yes
                  Build HDF5 Tools: yes
                   Build GIF Tools: no
                      Threadsafety: no
               Default API mapping: v114
    With deprecated public symbols: yes
            I/O filters (external): deflate(zlib),szip(no encoder)
                     Map (H5M) API: no
                        Direct VFD: no
                        Mirror VFD: no
                     Subfiling VFD: no
                (Read-Only) S3 VFD: no
              (Read-Only) HDFS VFD: no
    Packages w/ extra debug output: none
                       API tracing: no
              Using memory checker: no
            Function stack tracing: no
                  Use file locking: best-effort
         Strict file format checks: no
      Optimization instrumentation: no
```
netcdf though is not properly detecting the HDF5 is built for parallel.

**Comment by WardF** [comment]
Do you happen to have the `config.log` and/or `libnetcdf.settings` generated by netCDF? This looks very much like what happens when a different/unexpected `libhdf5` is being found and linked against, instead of the version expected.  The files above should either help us confirm that's what is happening, or help us figure out why netCDF isn't properly detecting that it should turn on parallel functionality.  Thanks!

**Comment by wkliao** [comment]
Try setting the following 2 environment variables and rerun configure command.
They tell netcdf-c where to find the HDF5 library.
```
export CPPFLAGS=/n/sw/helmod-rocky8/apps/MPI/gcc/12.2.0-fasrc01/openmpi/4.1.4-fasrc01/hdf5/1.14.0-fasrc01/include
export LDFLAGS=/n/sw/helmod-rocky8/apps/MPI/gcc/12.2.0-fasrc01/openmpi/4.1.4-fasrc01/hdf5/1.14.0-fasrc01/lib
```
