### ISSUE TITLE
Fix HDF4 support, broken since release 4.3.1.1

### ISSUE THREAD

**Issue by russrew** [Unidata/netcdf-c#21]
HDF4 support no longer works, failing to compile libsrc4/nc4file.c, although it worked fine in release 4.3.1.1.

To reproduce with autoconf build:

  CPPFLAGS="-I${H5DIR}/include -I${H4DIR}/include" LDFLAGS="-L${H5DIR}/lib -L${H4DIR}/lib" ../configure  --prefix=${NCDIR} --enable-hdf4 --enable-hdf4-file-tests && make check

which results in compile errors:

  ../../libsrc4/nc4file.c: In function 'nc4_open_hdf4_file':
  ../../libsrc4/nc4file.c:2346:16: error: 'NC_ATT_INFO_T' has no member named 'xtype'
  ../../libsrc4/nc4file.c:2351:48: error: 'NC_ATT_INFO_T' has no member named 'xtype'
    ...

**Comment by zxdawn** [comment]
@qkoziol Hi Quincey, I meet the same error when I'm using WRF model:
```
wrf.exe: nc4internal.c:902: nc4_type_free: Assertion `type->rc' failed.
```

However, this happened after two day's running, not happened at first.

compiler: intel 15.0.1
netcdf: 4.3.3.1
pnetcdf: 1.6.1
MPICH:3.1

**Comment by edhartnett** [comment]
Can you upgrade netcdf? Hdf4 works great in recent 4.6.2 release, for example.

**Comment by zxdawn** [comment]
> Can you upgrade netcdf? Hdf4 works great in recent 4.6.2 release, for example.

@edhartnett Thank you for your suggestion. But, netcdf 4.3.3.1 works fine for generating hundred files. This issue happened at one moment after that. If it's the problem of version, why not happen at first?

**Comment by zxdawn** [comment]
The complete description is on the [WRF forum](http://forum.mmm.ucar.edu/phpBB3/viewtopic.php?f=40&t=570&p=1805#p1805). I'm not sure it's related to `netcdf` or `tasks`.
